//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeDCartAccess.ThreeDCartService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://3dcart.com/", ConfigurationName="ThreeDCartService.cartAPISoap")]
    public interface cartAPISoap {
        
        // CODEGEN: Generating message contract since element name storeUrl from namespace http://3dcart.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getProduct", ReplyAction="*")]
        ThreeDCartAccess.ThreeDCartService.getProductResponse getProduct(ThreeDCartAccess.ThreeDCartService.getProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getProductResponse> getProductAsync(ThreeDCartAccess.ThreeDCartService.getProductRequest request);
        
        // CODEGEN: Generating message contract since element name storeUrl from namespace http://3dcart.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getCustomer", ReplyAction="*")]
        ThreeDCartAccess.ThreeDCartService.getCustomerResponse getCustomer(ThreeDCartAccess.ThreeDCartService.getCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getCustomerResponse> getCustomerAsync(ThreeDCartAccess.ThreeDCartService.getCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name storeUrl from namespace http://3dcart.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/editCustomer", ReplyAction="*")]
        ThreeDCartAccess.ThreeDCartService.editCustomerResponse editCustomer(ThreeDCartAccess.ThreeDCartService.editCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/editCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.editCustomerResponse> editCustomerAsync(ThreeDCartAccess.ThreeDCartService.editCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name storeUrl from namespace http://3dcart.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getProductCount", ReplyAction="*")]
        ThreeDCartAccess.ThreeDCartService.getProductCountResponse getProductCount(ThreeDCartAccess.ThreeDCartService.getProductCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getProductCount", ReplyAction="*")]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getProductCountResponse> getProductCountAsync(ThreeDCartAccess.ThreeDCartService.getProductCountRequest request);
        
        // CODEGEN: Generating message contract since element name storeUrl from namespace http://3dcart.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getCustomerCount", ReplyAction="*")]
        ThreeDCartAccess.ThreeDCartService.getCustomerCountResponse getCustomerCount(ThreeDCartAccess.ThreeDCartService.getCustomerCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getCustomerCount", ReplyAction="*")]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getCustomerCountResponse> getCustomerCountAsync(ThreeDCartAccess.ThreeDCartService.getCustomerCountRequest request);
        
        // CODEGEN: Generating message contract since element name storeUrl from namespace http://3dcart.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getOrderStatus", ReplyAction="*")]
        ThreeDCartAccess.ThreeDCartService.getOrderStatusResponse getOrderStatus(ThreeDCartAccess.ThreeDCartService.getOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getOrderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getOrderStatusResponse> getOrderStatusAsync(ThreeDCartAccess.ThreeDCartService.getOrderStatusRequest request);
        
        // CODEGEN: Generating message contract since element name storeUrl from namespace http://3dcart.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getProductInventory", ReplyAction="*")]
        ThreeDCartAccess.ThreeDCartService.getProductInventoryResponse getProductInventory(ThreeDCartAccess.ThreeDCartService.getProductInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getProductInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getProductInventoryResponse> getProductInventoryAsync(ThreeDCartAccess.ThreeDCartService.getProductInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name storeUrl from namespace http://3dcart.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/updateProductInventory", ReplyAction="*")]
        ThreeDCartAccess.ThreeDCartService.updateProductInventoryResponse updateProductInventory(ThreeDCartAccess.ThreeDCartService.updateProductInventoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/updateProductInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.updateProductInventoryResponse> updateProductInventoryAsync(ThreeDCartAccess.ThreeDCartService.updateProductInventoryRequest request);
        
        // CODEGEN: Generating message contract since element name storeUrl from namespace http://3dcart.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/updateOrderStatus", ReplyAction="*")]
        ThreeDCartAccess.ThreeDCartService.updateOrderStatusResponse updateOrderStatus(ThreeDCartAccess.ThreeDCartService.updateOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/updateOrderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.updateOrderStatusResponse> updateOrderStatusAsync(ThreeDCartAccess.ThreeDCartService.updateOrderStatusRequest request);
        
        // CODEGEN: Generating message contract since element name storeUrl from namespace http://3dcart.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/updateOrderShipment", ReplyAction="*")]
        ThreeDCartAccess.ThreeDCartService.updateOrderShipmentResponse updateOrderShipment(ThreeDCartAccess.ThreeDCartService.updateOrderShipmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/updateOrderShipment", ReplyAction="*")]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.updateOrderShipmentResponse> updateOrderShipmentAsync(ThreeDCartAccess.ThreeDCartService.updateOrderShipmentRequest request);
        
        // CODEGEN: Generating message contract since element name storeUrl from namespace http://3dcart.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getOrder", ReplyAction="*")]
        ThreeDCartAccess.ThreeDCartService.getOrderResponse getOrder(ThreeDCartAccess.ThreeDCartService.getOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getOrderResponse> getOrderAsync(ThreeDCartAccess.ThreeDCartService.getOrderRequest request);
        
        // CODEGEN: Generating message contract since element name storeUrl from namespace http://3dcart.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getOrderCount", ReplyAction="*")]
        ThreeDCartAccess.ThreeDCartService.getOrderCountResponse getOrderCount(ThreeDCartAccess.ThreeDCartService.getOrderCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getOrderCount", ReplyAction="*")]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getOrderCountResponse> getOrderCountAsync(ThreeDCartAccess.ThreeDCartService.getOrderCountRequest request);
        
        // CODEGEN: Generating message contract since element name storeUrl from namespace http://3dcart.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getCustomerLoginToken", ReplyAction="*")]
        ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenResponse getCustomerLoginToken(ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://3dcart.com/getCustomerLoginToken", ReplyAction="*")]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenResponse> getCustomerLoginTokenAsync(ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProduct", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getProductRequestBody Body;
        
        public getProductRequest() {
        }
        
        public getProductRequest(ThreeDCartAccess.ThreeDCartService.getProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storeUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int batchSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int startNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string productId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string callBackURL;
        
        public getProductRequestBody() {
        }
        
        public getProductRequestBody(string storeUrl, string userKey, int batchSize, int startNum, string productId, string callBackURL) {
            this.storeUrl = storeUrl;
            this.userKey = userKey;
            this.batchSize = batchSize;
            this.startNum = startNum;
            this.productId = productId;
            this.callBackURL = callBackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductResponse", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getProductResponseBody Body;
        
        public getProductResponse() {
        }
        
        public getProductResponse(ThreeDCartAccess.ThreeDCartService.getProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getProductResult;
        
        public getProductResponseBody() {
        }
        
        public getProductResponseBody(System.Xml.Linq.XElement getProductResult) {
            this.getProductResult = getProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCustomer", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getCustomerRequestBody Body;
        
        public getCustomerRequest() {
        }
        
        public getCustomerRequest(ThreeDCartAccess.ThreeDCartService.getCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storeUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int batchSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int startNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string customersFilter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string callBackURL;
        
        public getCustomerRequestBody() {
        }
        
        public getCustomerRequestBody(string storeUrl, string userKey, int batchSize, int startNum, string customersFilter, string callBackURL) {
            this.storeUrl = storeUrl;
            this.userKey = userKey;
            this.batchSize = batchSize;
            this.startNum = startNum;
            this.customersFilter = customersFilter;
            this.callBackURL = callBackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCustomerResponse", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getCustomerResponseBody Body;
        
        public getCustomerResponse() {
        }
        
        public getCustomerResponse(ThreeDCartAccess.ThreeDCartService.getCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getCustomerResult;
        
        public getCustomerResponseBody() {
        }
        
        public getCustomerResponseBody(System.Xml.Linq.XElement getCustomerResult) {
            this.getCustomerResult = getCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editCustomer", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.editCustomerRequestBody Body;
        
        public editCustomerRequest() {
        }
        
        public editCustomerRequest(ThreeDCartAccess.ThreeDCartService.editCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class editCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storeUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string customerData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string action;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string callBackURL;
        
        public editCustomerRequestBody() {
        }
        
        public editCustomerRequestBody(string storeUrl, string userKey, string customerData, string action, string callBackURL) {
            this.storeUrl = storeUrl;
            this.userKey = userKey;
            this.customerData = customerData;
            this.action = action;
            this.callBackURL = callBackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class editCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="editCustomerResponse", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.editCustomerResponseBody Body;
        
        public editCustomerResponse() {
        }
        
        public editCustomerResponse(ThreeDCartAccess.ThreeDCartService.editCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class editCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement editCustomerResult;
        
        public editCustomerResponseBody() {
        }
        
        public editCustomerResponseBody(System.Xml.Linq.XElement editCustomerResult) {
            this.editCustomerResult = editCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductCount", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getProductCountRequestBody Body;
        
        public getProductCountRequest() {
        }
        
        public getProductCountRequest(ThreeDCartAccess.ThreeDCartService.getProductCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getProductCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storeUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string callBackURL;
        
        public getProductCountRequestBody() {
        }
        
        public getProductCountRequestBody(string storeUrl, string userKey, string callBackURL) {
            this.storeUrl = storeUrl;
            this.userKey = userKey;
            this.callBackURL = callBackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductCountResponse", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getProductCountResponseBody Body;
        
        public getProductCountResponse() {
        }
        
        public getProductCountResponse(ThreeDCartAccess.ThreeDCartService.getProductCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getProductCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getProductCountResult;
        
        public getProductCountResponseBody() {
        }
        
        public getProductCountResponseBody(System.Xml.Linq.XElement getProductCountResult) {
            this.getProductCountResult = getProductCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCustomerCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCustomerCount", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getCustomerCountRequestBody Body;
        
        public getCustomerCountRequest() {
        }
        
        public getCustomerCountRequest(ThreeDCartAccess.ThreeDCartService.getCustomerCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getCustomerCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storeUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string callBackURL;
        
        public getCustomerCountRequestBody() {
        }
        
        public getCustomerCountRequestBody(string storeUrl, string userKey, string callBackURL) {
            this.storeUrl = storeUrl;
            this.userKey = userKey;
            this.callBackURL = callBackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCustomerCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCustomerCountResponse", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getCustomerCountResponseBody Body;
        
        public getCustomerCountResponse() {
        }
        
        public getCustomerCountResponse(ThreeDCartAccess.ThreeDCartService.getCustomerCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getCustomerCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getCustomerCountResult;
        
        public getCustomerCountResponseBody() {
        }
        
        public getCustomerCountResponseBody(System.Xml.Linq.XElement getCustomerCountResult) {
            this.getCustomerCountResult = getCustomerCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderStatus", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getOrderStatusRequestBody Body;
        
        public getOrderStatusRequest() {
        }
        
        public getOrderStatusRequest(ThreeDCartAccess.ThreeDCartService.getOrderStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getOrderStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storeUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string invoiceNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string callBackURL;
        
        public getOrderStatusRequestBody() {
        }
        
        public getOrderStatusRequestBody(string storeUrl, string userKey, string invoiceNum, string callBackURL) {
            this.storeUrl = storeUrl;
            this.userKey = userKey;
            this.invoiceNum = invoiceNum;
            this.callBackURL = callBackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderStatusResponse", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getOrderStatusResponseBody Body;
        
        public getOrderStatusResponse() {
        }
        
        public getOrderStatusResponse(ThreeDCartAccess.ThreeDCartService.getOrderStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getOrderStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getOrderStatusResult;
        
        public getOrderStatusResponseBody() {
        }
        
        public getOrderStatusResponseBody(System.Xml.Linq.XElement getOrderStatusResult) {
            this.getOrderStatusResult = getOrderStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductInventory", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getProductInventoryRequestBody Body;
        
        public getProductInventoryRequest() {
        }
        
        public getProductInventoryRequest(ThreeDCartAccess.ThreeDCartService.getProductInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getProductInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storeUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string productId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string callBackURL;
        
        public getProductInventoryRequestBody() {
        }
        
        public getProductInventoryRequestBody(string storeUrl, string userKey, string productId, string callBackURL) {
            this.storeUrl = storeUrl;
            this.userKey = userKey;
            this.productId = productId;
            this.callBackURL = callBackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductInventoryResponse", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getProductInventoryResponseBody Body;
        
        public getProductInventoryResponse() {
        }
        
        public getProductInventoryResponse(ThreeDCartAccess.ThreeDCartService.getProductInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getProductInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getProductInventoryResult;
        
        public getProductInventoryResponseBody() {
        }
        
        public getProductInventoryResponseBody(System.Xml.Linq.XElement getProductInventoryResult) {
            this.getProductInventoryResult = getProductInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateProductInventoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateProductInventory", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.updateProductInventoryRequestBody Body;
        
        public updateProductInventoryRequest() {
        }
        
        public updateProductInventoryRequest(ThreeDCartAccess.ThreeDCartService.updateProductInventoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class updateProductInventoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storeUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string productId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool replaceStock;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string callBackURL;
        
        public updateProductInventoryRequestBody() {
        }
        
        public updateProductInventoryRequestBody(string storeUrl, string userKey, string productId, int quantity, bool replaceStock, string callBackURL) {
            this.storeUrl = storeUrl;
            this.userKey = userKey;
            this.productId = productId;
            this.quantity = quantity;
            this.replaceStock = replaceStock;
            this.callBackURL = callBackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateProductInventoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateProductInventoryResponse", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.updateProductInventoryResponseBody Body;
        
        public updateProductInventoryResponse() {
        }
        
        public updateProductInventoryResponse(ThreeDCartAccess.ThreeDCartService.updateProductInventoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class updateProductInventoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement updateProductInventoryResult;
        
        public updateProductInventoryResponseBody() {
        }
        
        public updateProductInventoryResponseBody(System.Xml.Linq.XElement updateProductInventoryResult) {
            this.updateProductInventoryResult = updateProductInventoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateOrderStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateOrderStatus", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.updateOrderStatusRequestBody Body;
        
        public updateOrderStatusRequest() {
        }
        
        public updateOrderStatusRequest(ThreeDCartAccess.ThreeDCartService.updateOrderStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class updateOrderStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storeUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string invoiceNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string newStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string callBackURL;
        
        public updateOrderStatusRequestBody() {
        }
        
        public updateOrderStatusRequestBody(string storeUrl, string userKey, string invoiceNum, string newStatus, string callBackURL) {
            this.storeUrl = storeUrl;
            this.userKey = userKey;
            this.invoiceNum = invoiceNum;
            this.newStatus = newStatus;
            this.callBackURL = callBackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateOrderStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateOrderStatusResponse", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.updateOrderStatusResponseBody Body;
        
        public updateOrderStatusResponse() {
        }
        
        public updateOrderStatusResponse(ThreeDCartAccess.ThreeDCartService.updateOrderStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class updateOrderStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement updateOrderStatusResult;
        
        public updateOrderStatusResponseBody() {
        }
        
        public updateOrderStatusResponseBody(System.Xml.Linq.XElement updateOrderStatusResult) {
            this.updateOrderStatusResult = updateOrderStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateOrderShipmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateOrderShipment", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.updateOrderShipmentRequestBody Body;
        
        public updateOrderShipmentRequest() {
        }
        
        public updateOrderShipmentRequest(ThreeDCartAccess.ThreeDCartService.updateOrderShipmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class updateOrderShipmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storeUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string invoiceNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string shipmentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tracking;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string shipmentDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string callBackURL;
        
        public updateOrderShipmentRequestBody() {
        }
        
        public updateOrderShipmentRequestBody(string storeUrl, string userKey, string invoiceNum, string shipmentID, string tracking, string shipmentDate, string callBackURL) {
            this.storeUrl = storeUrl;
            this.userKey = userKey;
            this.invoiceNum = invoiceNum;
            this.shipmentID = shipmentID;
            this.tracking = tracking;
            this.shipmentDate = shipmentDate;
            this.callBackURL = callBackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateOrderShipmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateOrderShipmentResponse", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.updateOrderShipmentResponseBody Body;
        
        public updateOrderShipmentResponse() {
        }
        
        public updateOrderShipmentResponse(ThreeDCartAccess.ThreeDCartService.updateOrderShipmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class updateOrderShipmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement updateOrderShipmentResult;
        
        public updateOrderShipmentResponseBody() {
        }
        
        public updateOrderShipmentResponseBody(System.Xml.Linq.XElement updateOrderShipmentResult) {
            this.updateOrderShipmentResult = updateOrderShipmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrder", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getOrderRequestBody Body;
        
        public getOrderRequest() {
        }
        
        public getOrderRequest(ThreeDCartAccess.ThreeDCartService.getOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storeUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int batchSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int startNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool startFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string invoiceNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string dateFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string dateTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string callBackURL;
        
        public getOrderRequestBody() {
        }
        
        public getOrderRequestBody(string storeUrl, string userKey, int batchSize, int startNum, bool startFrom, string invoiceNum, string status, string dateFrom, string dateTo, string callBackURL) {
            this.storeUrl = storeUrl;
            this.userKey = userKey;
            this.batchSize = batchSize;
            this.startNum = startNum;
            this.startFrom = startFrom;
            this.invoiceNum = invoiceNum;
            this.status = status;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
            this.callBackURL = callBackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderResponse", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getOrderResponseBody Body;
        
        public getOrderResponse() {
        }
        
        public getOrderResponse(ThreeDCartAccess.ThreeDCartService.getOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getOrderResult;
        
        public getOrderResponseBody() {
        }
        
        public getOrderResponseBody(System.Xml.Linq.XElement getOrderResult) {
            this.getOrderResult = getOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderCount", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getOrderCountRequestBody Body;
        
        public getOrderCountRequest() {
        }
        
        public getOrderCountRequest(ThreeDCartAccess.ThreeDCartService.getOrderCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getOrderCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storeUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool startFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string invoiceNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dateFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string dateTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string callBackURL;
        
        public getOrderCountRequestBody() {
        }
        
        public getOrderCountRequestBody(string storeUrl, string userKey, bool startFrom, string invoiceNum, string status, string dateFrom, string dateTo, string callBackURL) {
            this.storeUrl = storeUrl;
            this.userKey = userKey;
            this.startFrom = startFrom;
            this.invoiceNum = invoiceNum;
            this.status = status;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
            this.callBackURL = callBackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderCountResponse", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getOrderCountResponseBody Body;
        
        public getOrderCountResponse() {
        }
        
        public getOrderCountResponse(ThreeDCartAccess.ThreeDCartService.getOrderCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getOrderCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getOrderCountResult;
        
        public getOrderCountResponseBody() {
        }
        
        public getOrderCountResponseBody(System.Xml.Linq.XElement getOrderCountResult) {
            this.getOrderCountResult = getOrderCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCustomerLoginTokenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCustomerLoginToken", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenRequestBody Body;
        
        public getCustomerLoginTokenRequest() {
        }
        
        public getCustomerLoginTokenRequest(ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getCustomerLoginTokenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string storeUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string customerEmail;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int timeToLive;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string callBackURL;
        
        public getCustomerLoginTokenRequestBody() {
        }
        
        public getCustomerLoginTokenRequestBody(string storeUrl, string userKey, string customerEmail, int timeToLive, string callBackURL) {
            this.storeUrl = storeUrl;
            this.userKey = userKey;
            this.customerEmail = customerEmail;
            this.timeToLive = timeToLive;
            this.callBackURL = callBackURL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCustomerLoginTokenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCustomerLoginTokenResponse", Namespace="http://3dcart.com/", Order=0)]
        public ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenResponseBody Body;
        
        public getCustomerLoginTokenResponse() {
        }
        
        public getCustomerLoginTokenResponse(ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://3dcart.com/")]
    public partial class getCustomerLoginTokenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getCustomerLoginTokenResult;
        
        public getCustomerLoginTokenResponseBody() {
        }
        
        public getCustomerLoginTokenResponseBody(System.Xml.Linq.XElement getCustomerLoginTokenResult) {
            this.getCustomerLoginTokenResult = getCustomerLoginTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface cartAPISoapChannel : ThreeDCartAccess.ThreeDCartService.cartAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class cartAPISoapClient : System.ServiceModel.ClientBase<ThreeDCartAccess.ThreeDCartService.cartAPISoap>, ThreeDCartAccess.ThreeDCartService.cartAPISoap {
        
        public cartAPISoapClient() {
        }
        
        public cartAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public cartAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cartAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cartAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThreeDCartAccess.ThreeDCartService.getProductResponse ThreeDCartAccess.ThreeDCartService.cartAPISoap.getProduct(ThreeDCartAccess.ThreeDCartService.getProductRequest request) {
            return base.Channel.getProduct(request);
        }
        
        public System.Xml.Linq.XElement getProduct(string storeUrl, string userKey, int batchSize, int startNum, string productId, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getProductRequest inValue = new ThreeDCartAccess.ThreeDCartService.getProductRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getProductRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.batchSize = batchSize;
            inValue.Body.startNum = startNum;
            inValue.Body.productId = productId;
            inValue.Body.callBackURL = callBackURL;
            ThreeDCartAccess.ThreeDCartService.getProductResponse retVal = ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getProduct(inValue);
            return retVal.Body.getProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getProductResponse> ThreeDCartAccess.ThreeDCartService.cartAPISoap.getProductAsync(ThreeDCartAccess.ThreeDCartService.getProductRequest request) {
            return base.Channel.getProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getProductResponse> getProductAsync(string storeUrl, string userKey, int batchSize, int startNum, string productId, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getProductRequest inValue = new ThreeDCartAccess.ThreeDCartService.getProductRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getProductRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.batchSize = batchSize;
            inValue.Body.startNum = startNum;
            inValue.Body.productId = productId;
            inValue.Body.callBackURL = callBackURL;
            return ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThreeDCartAccess.ThreeDCartService.getCustomerResponse ThreeDCartAccess.ThreeDCartService.cartAPISoap.getCustomer(ThreeDCartAccess.ThreeDCartService.getCustomerRequest request) {
            return base.Channel.getCustomer(request);
        }
        
        public System.Xml.Linq.XElement getCustomer(string storeUrl, string userKey, int batchSize, int startNum, string customersFilter, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getCustomerRequest inValue = new ThreeDCartAccess.ThreeDCartService.getCustomerRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getCustomerRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.batchSize = batchSize;
            inValue.Body.startNum = startNum;
            inValue.Body.customersFilter = customersFilter;
            inValue.Body.callBackURL = callBackURL;
            ThreeDCartAccess.ThreeDCartService.getCustomerResponse retVal = ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getCustomer(inValue);
            return retVal.Body.getCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getCustomerResponse> ThreeDCartAccess.ThreeDCartService.cartAPISoap.getCustomerAsync(ThreeDCartAccess.ThreeDCartService.getCustomerRequest request) {
            return base.Channel.getCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getCustomerResponse> getCustomerAsync(string storeUrl, string userKey, int batchSize, int startNum, string customersFilter, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getCustomerRequest inValue = new ThreeDCartAccess.ThreeDCartService.getCustomerRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getCustomerRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.batchSize = batchSize;
            inValue.Body.startNum = startNum;
            inValue.Body.customersFilter = customersFilter;
            inValue.Body.callBackURL = callBackURL;
            return ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThreeDCartAccess.ThreeDCartService.editCustomerResponse ThreeDCartAccess.ThreeDCartService.cartAPISoap.editCustomer(ThreeDCartAccess.ThreeDCartService.editCustomerRequest request) {
            return base.Channel.editCustomer(request);
        }
        
        public System.Xml.Linq.XElement editCustomer(string storeUrl, string userKey, string customerData, string action, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.editCustomerRequest inValue = new ThreeDCartAccess.ThreeDCartService.editCustomerRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.editCustomerRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.customerData = customerData;
            inValue.Body.action = action;
            inValue.Body.callBackURL = callBackURL;
            ThreeDCartAccess.ThreeDCartService.editCustomerResponse retVal = ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).editCustomer(inValue);
            return retVal.Body.editCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.editCustomerResponse> ThreeDCartAccess.ThreeDCartService.cartAPISoap.editCustomerAsync(ThreeDCartAccess.ThreeDCartService.editCustomerRequest request) {
            return base.Channel.editCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.editCustomerResponse> editCustomerAsync(string storeUrl, string userKey, string customerData, string action, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.editCustomerRequest inValue = new ThreeDCartAccess.ThreeDCartService.editCustomerRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.editCustomerRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.customerData = customerData;
            inValue.Body.action = action;
            inValue.Body.callBackURL = callBackURL;
            return ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).editCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThreeDCartAccess.ThreeDCartService.getProductCountResponse ThreeDCartAccess.ThreeDCartService.cartAPISoap.getProductCount(ThreeDCartAccess.ThreeDCartService.getProductCountRequest request) {
            return base.Channel.getProductCount(request);
        }
        
        public System.Xml.Linq.XElement getProductCount(string storeUrl, string userKey, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getProductCountRequest inValue = new ThreeDCartAccess.ThreeDCartService.getProductCountRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getProductCountRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.callBackURL = callBackURL;
            ThreeDCartAccess.ThreeDCartService.getProductCountResponse retVal = ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getProductCount(inValue);
            return retVal.Body.getProductCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getProductCountResponse> ThreeDCartAccess.ThreeDCartService.cartAPISoap.getProductCountAsync(ThreeDCartAccess.ThreeDCartService.getProductCountRequest request) {
            return base.Channel.getProductCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getProductCountResponse> getProductCountAsync(string storeUrl, string userKey, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getProductCountRequest inValue = new ThreeDCartAccess.ThreeDCartService.getProductCountRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getProductCountRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.callBackURL = callBackURL;
            return ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getProductCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThreeDCartAccess.ThreeDCartService.getCustomerCountResponse ThreeDCartAccess.ThreeDCartService.cartAPISoap.getCustomerCount(ThreeDCartAccess.ThreeDCartService.getCustomerCountRequest request) {
            return base.Channel.getCustomerCount(request);
        }
        
        public System.Xml.Linq.XElement getCustomerCount(string storeUrl, string userKey, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getCustomerCountRequest inValue = new ThreeDCartAccess.ThreeDCartService.getCustomerCountRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getCustomerCountRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.callBackURL = callBackURL;
            ThreeDCartAccess.ThreeDCartService.getCustomerCountResponse retVal = ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getCustomerCount(inValue);
            return retVal.Body.getCustomerCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getCustomerCountResponse> ThreeDCartAccess.ThreeDCartService.cartAPISoap.getCustomerCountAsync(ThreeDCartAccess.ThreeDCartService.getCustomerCountRequest request) {
            return base.Channel.getCustomerCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getCustomerCountResponse> getCustomerCountAsync(string storeUrl, string userKey, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getCustomerCountRequest inValue = new ThreeDCartAccess.ThreeDCartService.getCustomerCountRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getCustomerCountRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.callBackURL = callBackURL;
            return ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getCustomerCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThreeDCartAccess.ThreeDCartService.getOrderStatusResponse ThreeDCartAccess.ThreeDCartService.cartAPISoap.getOrderStatus(ThreeDCartAccess.ThreeDCartService.getOrderStatusRequest request) {
            return base.Channel.getOrderStatus(request);
        }
        
        public System.Xml.Linq.XElement getOrderStatus(string storeUrl, string userKey, string invoiceNum, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getOrderStatusRequest inValue = new ThreeDCartAccess.ThreeDCartService.getOrderStatusRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getOrderStatusRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.invoiceNum = invoiceNum;
            inValue.Body.callBackURL = callBackURL;
            ThreeDCartAccess.ThreeDCartService.getOrderStatusResponse retVal = ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getOrderStatus(inValue);
            return retVal.Body.getOrderStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getOrderStatusResponse> ThreeDCartAccess.ThreeDCartService.cartAPISoap.getOrderStatusAsync(ThreeDCartAccess.ThreeDCartService.getOrderStatusRequest request) {
            return base.Channel.getOrderStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getOrderStatusResponse> getOrderStatusAsync(string storeUrl, string userKey, string invoiceNum, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getOrderStatusRequest inValue = new ThreeDCartAccess.ThreeDCartService.getOrderStatusRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getOrderStatusRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.invoiceNum = invoiceNum;
            inValue.Body.callBackURL = callBackURL;
            return ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getOrderStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThreeDCartAccess.ThreeDCartService.getProductInventoryResponse ThreeDCartAccess.ThreeDCartService.cartAPISoap.getProductInventory(ThreeDCartAccess.ThreeDCartService.getProductInventoryRequest request) {
            return base.Channel.getProductInventory(request);
        }
        
        public System.Xml.Linq.XElement getProductInventory(string storeUrl, string userKey, string productId, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getProductInventoryRequest inValue = new ThreeDCartAccess.ThreeDCartService.getProductInventoryRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getProductInventoryRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.productId = productId;
            inValue.Body.callBackURL = callBackURL;
            ThreeDCartAccess.ThreeDCartService.getProductInventoryResponse retVal = ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getProductInventory(inValue);
            return retVal.Body.getProductInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getProductInventoryResponse> ThreeDCartAccess.ThreeDCartService.cartAPISoap.getProductInventoryAsync(ThreeDCartAccess.ThreeDCartService.getProductInventoryRequest request) {
            return base.Channel.getProductInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getProductInventoryResponse> getProductInventoryAsync(string storeUrl, string userKey, string productId, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getProductInventoryRequest inValue = new ThreeDCartAccess.ThreeDCartService.getProductInventoryRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getProductInventoryRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.productId = productId;
            inValue.Body.callBackURL = callBackURL;
            return ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getProductInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThreeDCartAccess.ThreeDCartService.updateProductInventoryResponse ThreeDCartAccess.ThreeDCartService.cartAPISoap.updateProductInventory(ThreeDCartAccess.ThreeDCartService.updateProductInventoryRequest request) {
            return base.Channel.updateProductInventory(request);
        }
        
        public System.Xml.Linq.XElement updateProductInventory(string storeUrl, string userKey, string productId, int quantity, bool replaceStock, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.updateProductInventoryRequest inValue = new ThreeDCartAccess.ThreeDCartService.updateProductInventoryRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.updateProductInventoryRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.productId = productId;
            inValue.Body.quantity = quantity;
            inValue.Body.replaceStock = replaceStock;
            inValue.Body.callBackURL = callBackURL;
            ThreeDCartAccess.ThreeDCartService.updateProductInventoryResponse retVal = ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).updateProductInventory(inValue);
            return retVal.Body.updateProductInventoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.updateProductInventoryResponse> ThreeDCartAccess.ThreeDCartService.cartAPISoap.updateProductInventoryAsync(ThreeDCartAccess.ThreeDCartService.updateProductInventoryRequest request) {
            return base.Channel.updateProductInventoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.updateProductInventoryResponse> updateProductInventoryAsync(string storeUrl, string userKey, string productId, int quantity, bool replaceStock, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.updateProductInventoryRequest inValue = new ThreeDCartAccess.ThreeDCartService.updateProductInventoryRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.updateProductInventoryRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.productId = productId;
            inValue.Body.quantity = quantity;
            inValue.Body.replaceStock = replaceStock;
            inValue.Body.callBackURL = callBackURL;
            return ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).updateProductInventoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThreeDCartAccess.ThreeDCartService.updateOrderStatusResponse ThreeDCartAccess.ThreeDCartService.cartAPISoap.updateOrderStatus(ThreeDCartAccess.ThreeDCartService.updateOrderStatusRequest request) {
            return base.Channel.updateOrderStatus(request);
        }
        
        public System.Xml.Linq.XElement updateOrderStatus(string storeUrl, string userKey, string invoiceNum, string newStatus, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.updateOrderStatusRequest inValue = new ThreeDCartAccess.ThreeDCartService.updateOrderStatusRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.updateOrderStatusRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.invoiceNum = invoiceNum;
            inValue.Body.newStatus = newStatus;
            inValue.Body.callBackURL = callBackURL;
            ThreeDCartAccess.ThreeDCartService.updateOrderStatusResponse retVal = ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).updateOrderStatus(inValue);
            return retVal.Body.updateOrderStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.updateOrderStatusResponse> ThreeDCartAccess.ThreeDCartService.cartAPISoap.updateOrderStatusAsync(ThreeDCartAccess.ThreeDCartService.updateOrderStatusRequest request) {
            return base.Channel.updateOrderStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.updateOrderStatusResponse> updateOrderStatusAsync(string storeUrl, string userKey, string invoiceNum, string newStatus, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.updateOrderStatusRequest inValue = new ThreeDCartAccess.ThreeDCartService.updateOrderStatusRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.updateOrderStatusRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.invoiceNum = invoiceNum;
            inValue.Body.newStatus = newStatus;
            inValue.Body.callBackURL = callBackURL;
            return ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).updateOrderStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThreeDCartAccess.ThreeDCartService.updateOrderShipmentResponse ThreeDCartAccess.ThreeDCartService.cartAPISoap.updateOrderShipment(ThreeDCartAccess.ThreeDCartService.updateOrderShipmentRequest request) {
            return base.Channel.updateOrderShipment(request);
        }
        
        public System.Xml.Linq.XElement updateOrderShipment(string storeUrl, string userKey, string invoiceNum, string shipmentID, string tracking, string shipmentDate, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.updateOrderShipmentRequest inValue = new ThreeDCartAccess.ThreeDCartService.updateOrderShipmentRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.updateOrderShipmentRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.invoiceNum = invoiceNum;
            inValue.Body.shipmentID = shipmentID;
            inValue.Body.tracking = tracking;
            inValue.Body.shipmentDate = shipmentDate;
            inValue.Body.callBackURL = callBackURL;
            ThreeDCartAccess.ThreeDCartService.updateOrderShipmentResponse retVal = ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).updateOrderShipment(inValue);
            return retVal.Body.updateOrderShipmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.updateOrderShipmentResponse> ThreeDCartAccess.ThreeDCartService.cartAPISoap.updateOrderShipmentAsync(ThreeDCartAccess.ThreeDCartService.updateOrderShipmentRequest request) {
            return base.Channel.updateOrderShipmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.updateOrderShipmentResponse> updateOrderShipmentAsync(string storeUrl, string userKey, string invoiceNum, string shipmentID, string tracking, string shipmentDate, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.updateOrderShipmentRequest inValue = new ThreeDCartAccess.ThreeDCartService.updateOrderShipmentRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.updateOrderShipmentRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.invoiceNum = invoiceNum;
            inValue.Body.shipmentID = shipmentID;
            inValue.Body.tracking = tracking;
            inValue.Body.shipmentDate = shipmentDate;
            inValue.Body.callBackURL = callBackURL;
            return ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).updateOrderShipmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThreeDCartAccess.ThreeDCartService.getOrderResponse ThreeDCartAccess.ThreeDCartService.cartAPISoap.getOrder(ThreeDCartAccess.ThreeDCartService.getOrderRequest request) {
            return base.Channel.getOrder(request);
        }
        
        public System.Xml.Linq.XElement getOrder(string storeUrl, string userKey, int batchSize, int startNum, bool startFrom, string invoiceNum, string status, string dateFrom, string dateTo, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getOrderRequest inValue = new ThreeDCartAccess.ThreeDCartService.getOrderRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getOrderRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.batchSize = batchSize;
            inValue.Body.startNum = startNum;
            inValue.Body.startFrom = startFrom;
            inValue.Body.invoiceNum = invoiceNum;
            inValue.Body.status = status;
            inValue.Body.dateFrom = dateFrom;
            inValue.Body.dateTo = dateTo;
            inValue.Body.callBackURL = callBackURL;
            ThreeDCartAccess.ThreeDCartService.getOrderResponse retVal = ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getOrder(inValue);
            return retVal.Body.getOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getOrderResponse> ThreeDCartAccess.ThreeDCartService.cartAPISoap.getOrderAsync(ThreeDCartAccess.ThreeDCartService.getOrderRequest request) {
            return base.Channel.getOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getOrderResponse> getOrderAsync(string storeUrl, string userKey, int batchSize, int startNum, bool startFrom, string invoiceNum, string status, string dateFrom, string dateTo, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getOrderRequest inValue = new ThreeDCartAccess.ThreeDCartService.getOrderRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getOrderRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.batchSize = batchSize;
            inValue.Body.startNum = startNum;
            inValue.Body.startFrom = startFrom;
            inValue.Body.invoiceNum = invoiceNum;
            inValue.Body.status = status;
            inValue.Body.dateFrom = dateFrom;
            inValue.Body.dateTo = dateTo;
            inValue.Body.callBackURL = callBackURL;
            return ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThreeDCartAccess.ThreeDCartService.getOrderCountResponse ThreeDCartAccess.ThreeDCartService.cartAPISoap.getOrderCount(ThreeDCartAccess.ThreeDCartService.getOrderCountRequest request) {
            return base.Channel.getOrderCount(request);
        }
        
        public System.Xml.Linq.XElement getOrderCount(string storeUrl, string userKey, bool startFrom, string invoiceNum, string status, string dateFrom, string dateTo, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getOrderCountRequest inValue = new ThreeDCartAccess.ThreeDCartService.getOrderCountRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getOrderCountRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.startFrom = startFrom;
            inValue.Body.invoiceNum = invoiceNum;
            inValue.Body.status = status;
            inValue.Body.dateFrom = dateFrom;
            inValue.Body.dateTo = dateTo;
            inValue.Body.callBackURL = callBackURL;
            ThreeDCartAccess.ThreeDCartService.getOrderCountResponse retVal = ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getOrderCount(inValue);
            return retVal.Body.getOrderCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getOrderCountResponse> ThreeDCartAccess.ThreeDCartService.cartAPISoap.getOrderCountAsync(ThreeDCartAccess.ThreeDCartService.getOrderCountRequest request) {
            return base.Channel.getOrderCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getOrderCountResponse> getOrderCountAsync(string storeUrl, string userKey, bool startFrom, string invoiceNum, string status, string dateFrom, string dateTo, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getOrderCountRequest inValue = new ThreeDCartAccess.ThreeDCartService.getOrderCountRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getOrderCountRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.startFrom = startFrom;
            inValue.Body.invoiceNum = invoiceNum;
            inValue.Body.status = status;
            inValue.Body.dateFrom = dateFrom;
            inValue.Body.dateTo = dateTo;
            inValue.Body.callBackURL = callBackURL;
            return ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getOrderCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenResponse ThreeDCartAccess.ThreeDCartService.cartAPISoap.getCustomerLoginToken(ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenRequest request) {
            return base.Channel.getCustomerLoginToken(request);
        }
        
        public System.Xml.Linq.XElement getCustomerLoginToken(string storeUrl, string userKey, string customerEmail, int timeToLive, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenRequest inValue = new ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.customerEmail = customerEmail;
            inValue.Body.timeToLive = timeToLive;
            inValue.Body.callBackURL = callBackURL;
            ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenResponse retVal = ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getCustomerLoginToken(inValue);
            return retVal.Body.getCustomerLoginTokenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenResponse> ThreeDCartAccess.ThreeDCartService.cartAPISoap.getCustomerLoginTokenAsync(ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenRequest request) {
            return base.Channel.getCustomerLoginTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenResponse> getCustomerLoginTokenAsync(string storeUrl, string userKey, string customerEmail, int timeToLive, string callBackURL) {
            ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenRequest inValue = new ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenRequest();
            inValue.Body = new ThreeDCartAccess.ThreeDCartService.getCustomerLoginTokenRequestBody();
            inValue.Body.storeUrl = storeUrl;
            inValue.Body.userKey = userKey;
            inValue.Body.customerEmail = customerEmail;
            inValue.Body.timeToLive = timeToLive;
            inValue.Body.callBackURL = callBackURL;
            return ((ThreeDCartAccess.ThreeDCartService.cartAPISoap)(this)).getCustomerLoginTokenAsync(inValue);
        }
    }
}
